spring:
#  security:
#    basic:
#      enabled: true               # 开启基于HTTP basic的认证
#    user:
#      name: admin                  # 配置登录的账号是admin
#      password: admin       # 配置登录的密码是admin

server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名
  client:
    #false表示不像客户中心注册自己
    register-with-eureka: false
    #false表示自己就是客户中心，我得 职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
       defaultZone: http://eureka7001.com:7001/eureka/ #集群版
#      defaultZone: http://admin:admin@eureka7001.com:7001/eureka/ #集群版-用户认证

      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机版
    #server:
    #enable-self-preservation: false #不启用默认的保护机制，    #eviction-interval-timer-in-ms: 2000