
spring:
  profiles:
    active: @env@
#  security:
#    basic:
#      enabled: true               # 开启基于HTTP basic的认证
#    user:
#      name: admin                  # 配置登录的账号是admin
#      password: admin       # 配置登录的密码是admin

server:
  port: 7002
eureka:
  instance:
    prefer-ip-address: true #以ip方法注册,docker布署时必须设置为true，否则fegin不能调用
    hostname: eureka7002.com #eureka服务端的实例名
    instance-id: eureka7002.com
    #eureka是使用hostname进行注册的，使用IP进行注册
    appname: ${spring.application.name}
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 15
  server:
    # 设为false，关闭自我保护
    enable-self-preservation: false
    #自我保护系数（默认0.85）
    renewal-percent-threshold: 0.85
    #禁用Eureka的ReadOnlyMap缓存
    use-read-only-response-cache: false
    # 清理无效节点间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 3000
    #注册信息缓存有效时长（s），默认180秒
    response-cache-auto-expiration-in-seconds: 15
    #注册信息缓存更新间隔（s），默认30秒
    response-cache-update-interval-ms: 5000
    #设置eureka server同步失败的等待时间，默认5分钟，在这期间它不向客户端提供服务注册信息
    wait-time-in-ms-when-sync-empty: 5
    #设置eureka server同步失败的重试次数，默认为5次
    number-of-replication-retries: 5
  client:
    #false表示不像客户中心注册自己
    register-with-eureka: false
    #false表示自己就是客户中心，我得 职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://172.17.0.5:7001/eureka/ #集群版
#       defaultZone: http://eureka7001.com:7001/eureka/ #集群版
#      defaultZone: http://admin:admin@eureka7001.com:7001/eureka/ #集群版-用户认证

      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机版
    #server:
    #enable-self-preservation: false #不启用默认的保护机制，    #eviction-interval-timer-in-ms: 2000