spring:
  main:
    allow-bean-definition-overriding: true
#    security:
#    basic:
#      enabled: true               # 开启基于HTTP basic的认证
#    user:
#      name: admin                  # 配置登录的账号是admin
#      password: admin       # 配置登录的密码是admin
  application:
    name: cloud-order-service #服务名
  datasource:  #数据库
    url: jdbc:mysql://localhost:3306/dockermysql?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#  thymeleaf:
#    cache: true
#    encoding: UTF-8
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5

lock:
  key: redis_key

server:
  port: 80

# thymeleaf

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
#      defaultZone: http://admin:admin@eureka7001.com:7001/eureka/,http://admin:admin@eureka7002.com:7002/eureka/ #集群版-用户认证

### 针对单个服务的 Ribbon 配置

### 针对单个服务的 Ribbon 配置
CLOUD-PAYMENT-SERVICE:  #服务提供名称
  ribbon:
    # 基于配置文件形式的 针对单个服务的 Ribbon 负载均衡策略
    NFLoadBalancerRuleClassName: com.lb.LoadBalancerConfig  #自定义负载均衡策略

feign:
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 6000 #默认的连接超时时间1秒,若1秒没有返回数据,自动的触发降级逻辑
        circuitBreaker:
          enabled: true
          requestVolumeThreshold: 5
          errorThresholdPercentage: 10
          sleepWindowInMilliseconds: 10000

#  在被监控的服务上添加暴露点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
#       include: '*'   #'*'代表开放所有端点。

#mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml


#showSql
logging:
  level:
    com:
      yu:
        dao : debug

