server:
  port: 7300
spring:
#  security:
#    basic:
#      enabled: true               # 开启基于HTTP basic的认证
#    user:
#      name: admin                  # 配置登录的账号是admin
#      password: admin       # 配置登录的密码是admin
  cloud:
    gateway:
      routes:
        - id: order-routes          #请求地址：http://localhost:7300/get/openfeign/1
          uri: http://localhost:80  #eureka注册服务ip
          predicates:               #路径相匹配的进行路由
            - Path=/get/openfeign/**
        #实现payment8001,8002服务动态路由负载均衡   请求地址：http://localhost:7300/mybatis/model/4
        - id: payment_routes #  payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          predicates:
            - Path=/mybatis/model/**
        - id: order_test #  payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名  http://localhost:7300/get/modelparams?id=1&modelId=343434343
          uri: lb://CLOUD-ORDER-SERVICE   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          predicates:
            - Path=/get/modelparams/**
        - id: order_test #  payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名  http://localhost:7300/get/modelparams?id=1&modelId=343434343
          uri: lb://CLOUD-ORDER-SERVICE   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          predicates:
            - Path=/post/model/**
    loadbalancer:
      ribbon:
        enabled: false
  application:
    name: cloud-gateway
  datasource:  #数据库
    url: jdbc:mysql://192.168.102.115:3306/testgroup?useUnicode=true&characterEncoding=UTF-8
    username: testgroup
    password: Sgcc_1234
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
#      defaultZone: http://admin:admin@eureka7001.com:7001/eureka/,http://admin:admin@eureka7002.com:7002/eureka/ #集群版-用户认证
  instance:
    prefer-ip-address: true