

spring:
  profiles:
    active: @env@
  cloud:
    stream:
      bindings:
        log_input:            #接收消息
          destination: kite.log.messages
          binder: local_rabbit
          group: logConsumer-group1
        #        model_input:            #接收消息
        #          destination: log.model.messages
        #          binder: local_rabbit
        #          group: modelConsumer-group1
        #        log_output:          #推送消息
        #          destination: kite.log.messages
        #          binder: local_rabbit
        #          group: logConsumer-group1
        log_format_input:
          destination: kite.log.format.messages
          binder: local_rabbit
          group: logFormat-group1
      #        log_format_output:
      #          destination: kite.log.format.messages
      #          binder: local_rabbit
      #          group: logFormat-group1
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: admin
  #  security:
  #    basic:
  #      enabled: true               # 开启基于HTTP basic的认证
  #    user:
  #      name: admin                  # 配置登录的账号是admin
  #      password: admin             # 配置登录的密码是admin
  application:
    name: cloud-payment-service #服务名
  datasource:  #数据库
    url: jdbc:mysql://localhost:3306/dockermysql?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    #指示此实例是否应将其信息注册到eureka服务器以供其他服务发现，默认为false
    register-with-eureka: true
    #是否从Server获取注册信息
    fetch-registry: true
    #定时从Eureka Server拉取服务注册信息的间隔时间(默认30秒，单位：s/秒）
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
      #      defaultZone: http://admin:admin@eureka7001.com:7001/eureka/,http://admin:admin@eureka7002.com:7002/eureka/ #集群版-用户认证
      #defaultZone: http://eureka7001.com:7001/eureka  #单机版
  instance:
    instance-id: payment8002
    prefer-ip-address: true
    #实例续约间隔时间(默认30秒)
    lease-renewal-interval-in-seconds: 5
    #实例超时时间，表示*秒后没有续约，Server就认为他不可用了，随之就会将其剔除。
    lease-expiration-duration-in-seconds: 15
    status-page-url-path: management/info
    health-check-url-path: management/health


#mybatis配置
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yu.mybatis.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    # 热加载mapper文件
    refresh: true
    db-config:
      db-type: mysql

server:
  port: 8002 #服务端口

#showSql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.yu.mybatis: DEBUG

app_id: 2021000116682104
alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm1ri3uNj3HiQ+rUxhHRJknuSx0FrkSFLkHXqyT5MmlGpIiZ4dVRfNRkp7f27ptmgzy6xBs0jKRPh381Oa4ydqjaDIeSZ+jxWCKsyYRZh3+cPzL91pb/XjCA3khIU6Vgp3IEKRMGq9VsONvqehu1BZeA5INW56Lh4bd8tV/pfPvy+w8MIniRbdsRleFKOSE6AdvljecJH5wzFT4GtsLRsaPG1QgWhJ7d1MnbiZzGSJNyVaGoCa175JC1c72mkdHp0s2/ClEAzlJfcwU78UC9pvBKL3763sNT6hDAibYlWwYjAcGJ0teKc6uaJmG53b7t8QbFQKq0EXQaD//FK8jjXIQIDAQAB
merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDKyuEGNQ7vIsuK8oyiu7+ahwJ2tvWaZTrB+cttDs4MjQvANpppALNrHNahbkAga52tuswAYimVVpAjAFFridiCg34017hfwQHAw2SgFVBamjB1NCmrYkwEyJGaY7InP4yThWwTG9p4I4bLgTz7Yj5xvXKIy0pl1hStqtO1WKGBU+Q9tJ+4y2PEpSys7iE9ZSbN0zLxqJzSJ0W76s3uckx7MmovYleiXkxu9zBkcfY1924cqzjiBRDQBVhCAnpiYMhcQwDF9spbqZb8kyPKH+Oc25S2wJeEdlBO3+CF3LfBdR/GsJuPphpwLF0Owrxg8OPAS9eRbwhJWz+R5tOkUEX3AgMBAAECggEBAIPpMDKfdNVs5sW9PGnmgp370Eh0fpIt4uimmgKYrMNRRCGF4y8GO68jFSHw21m7ZtfJOEXPlIkFw8BgxpWTFvjem8u3vsDahU9kSiIvexNUVM0IX0qSKCy8Yqnwy8Pn/INBOKm9ZoDbayUZLhe/Mis+NjBxPDW96bmF8yx1OKksReQ+rx8O/L92csvOinZMJplKc0frmsqBOeSirl+kTDDMVeL1qndiBBGWhZ+D8x/3GgOc54qFAU9UdbBVTXrsFppgPBYJQ1aZexWWeuJKxc5gN1d/TRKLpExe/pgV0x3nOrB6DNzoxQl2I7wMkxa7bIT3XRFI71yasvfHsLE7RrECgYEA8GESuWeBAaHeSRNlIj/Obvrk6Hx9hnVHla9N+3PJXWUIdOu/2VKyFfSn6ll6A6bnhAttgMg7gRMLIHnT0ycTBBkLnfLXEbuVzRR7yA3YZ6WzfraJpBqJHULqWJmFTZzgqGldm3HGyEnwS2w0lqvFNSHkKEYDALMgvCi3K7gPurUCgYEA1/iEVYXMjWgFb/BWdHuGeYeeq8ZswWnCwJ/U54Hcr/pPDcgQL+bLsfVQ2ginMsEn5ijiRxM25HgQRlVt/y6QPBAPMlyGoR82sU2UwVmj+aJymYP88AQJ6TgdAMnhn0c3M9s2Q4NKKj/q64NZwF5nrZuJBnMapNEUKrxdndpI7XsCgYEAzBuhKo0Ynao0dRhi55IGV3XyqPYMH/+1qQQR01Gdyg/f/mevn3j4fmwfqH4RfMhcDWMmuBNNc2wYJptLoh+rpe8eTh/FPulpaZnbASPAfUHWB+I3PYDKrG4FTvYMmrp6iIXvVe5mO+uMfn6CqO1xpowAj7HjGtT/FsX7wsOnl4ECgYBl+5lp1SOxhnRC1qfMm2P10V/Q14MVlf57/T2JEJ6Ijtdzt4xFQmPfperG+p0Rb3qKybWIQH+ERVnSDJdDj9ZWNnMmoeCFBvtJoEvlPZIb2GTrLxNqt02CzpeLfslG8FcV6qbmHIISD1q8WasxFqM4rKB45jOnrn8qawZ9+szDLwKBgEHMPkXFPWp/6XgjSOD66M7saY1JBCjwJ4UkwgU+jFIBIWs7GC1POtQEErnzN2FCGQkC83C8A4w8dBx2UJw8V+mNgdeWE2dda259R0pYF4MDe5JOzFCYitP0YoqG81tx0TtsNFfodBbQ5z937Q2XVN++DqAUk1Y/g4QISdm5gTaS
notify_url: http://zfb.vaiwan.com/alipay/callback
return_url: http://zfb.vaiwan.com/alipay/show
gatewayUrl: https://openapi.alipaydev.com/gateway.do
sign_type: RSA2
charset: UTF-8

qrcode_path: D:/appQrCode/